use serde::{Deserialize, Serialize};
use sqlx::Encode;

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize, Encode)]
#[serde(rename_all = "PascalCase")]
pub enum Country {
    Afghanistan,
    Albania,
    Algeria,
    Andorra,
    Angola,
    #[serde(rename = "Antigua and Barbuda")]
    AntiguaAndBarbuda,
    Argentina,
    Armenia,
    Aruba,
    Australia,
    Austria,
    Azerbaijan,
    Bahrain,
    Barbados,
    Belarus,
    Belgium,
    Benin,
    Bermuda,
    Bolivia,
    Bonaire,
    #[serde(rename = "Bosnia and Herzegovina")]
    BosniaHerzegovina,
    Brazil,
    #[serde(rename = "Brunei Darussalam")]
    BruneiDarussalam,
    Bulgaria,
    #[serde(rename = "Burkina Faso")]
    BurkinaFaso,
    Burundi,
    Cameroon,
    Canada,
    #[serde(rename = "Cape Verde")]
    CapeVerde,
    #[serde(rename = "Central African Republic")]
    CentralAfricanRepublic,
    Chad,
    Chile,
    China,
    Taiwan,
    Colombia,
    Comoros,
    Congo,
    #[serde(rename = "Costa Rica")]
    CostaRica,
    #[serde(rename = "Ivory Coast")]
    CoteDIvoire,
    Croatia,
    CSSR,
    Cuba,
    Curacao,
    Cyprus,
    #[serde(rename = "Czech Republic")]
    CzechRepublic,
    Denmark,
    Djibouti,
    Dominica,
    #[serde(rename = "Dominican Republic")]
    DominicanRepublic,
    #[serde(rename = "DR Congo")]
    DRCongo,
    Ecuador,
    Egypt,
    #[serde(rename = "El Salvador")]
    ElSalvador,
    England,
    #[serde(rename = "Equitorial Guinea")]
    EquatorialGuinea,
    Eritrea,
    Estonia,
    Ethiopia,
    Europe,
    #[serde(rename = "Faroe Islands")]
    FaroeIslands,
    Finland,
    France,
    #[serde(rename = "French Guiana")]
    FrenchGuiana,
    Gabon,
    Georgia,
    Germany,
    Ghana,
    Greece,
    Grenada,
    Guadeloupe,
    Guatemala,
    Guernsey,
    Guinea,
    #[serde(rename = "Guinea Bissau")]
    GuineaBissau,
    Guyana,
    Haiti,
    Honduras,
    Hongkong,
    Hungary,
    Iceland,
    India,
    Indonesia,
    Iran,
    Iraq,
    Ireland,
    #[serde(rename = "Isle of Man")]
    IsleOfMan,
    Israel,
    Italy,
    Jamaica,
    Japan,
    Jersey,
    Jordan,
    JugoslawienSFR,
    Kazakhstan,
    Kenya,
    #[serde(rename = "North Korea")]
    NorthKorea,
    #[serde(rename = "South Korea")]
    SouthKorea,
    Kosovo,
    Kuwait,
    Kyrgyzstan,
    Laos,
    Latvia,
    Lebanon,
    Liberia,
    Libya,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    Macao,
    Madagascar,
    Malawi,
    Malaysia,
    Mali,
    Malta,
    Martinique,
    Mauritania,
    Mauritius,
    Mayotte,
    Mexico,
    Moldova,
    Monaco,
    Montenegro,
    Montserrat,
    Morocco,
    Mozambique,
    Netherlands,
    #[serde(rename = "Netherlands Antilles")]
    NetherlandsAntilles,
    Neukaledonien,
    #[serde(rename = "New Zealand")]
    NewZealand,
    Nicaragua,
    Niger,
    Nigeria,
    #[serde(rename = "North Macedonia")]
    NorthMacedonia,
    #[serde(rename = "Northern Ireland")]
    NorthernIreland,
    Norway,
    Oman,
    Pakistan,
    Palestine,
    Panama,
    #[serde(rename = "Papua New Guinea")]
    PapuaNewGuinea,
    Paraguay,
    Peru,
    Philippines,
    Poland,
    Portugal,
    Qatar,
    Reunion,
    Romania,
    Russia,
    Rwanda,
    #[serde(rename = "Saint Martin")]
    SaintMartin,
    #[serde(rename = "San Marino")]
    SanMarino,
    #[serde(rename = "Sao Tome and Principe")]
    SaoTomeAndPrincipe,
    #[serde(rename = "Saudi Arabia")]
    SaudiArabia,
    Scotland,
    Senegal,
    Serbia,
    #[serde(rename = "Serbia and Montenegro")]
    SerbiaAndMontenegro,
    Seychelles,
    #[serde(rename = "Sierra Leone")]
    SierraLeone,
    Singapore,
    #[serde(rename = "Sint Maarten")]
    SintMaarten,
    Slovakia,
    Slovenia,
    Somalia,
    #[serde(rename = "South Africa")]
    SouthAfrica,
    #[serde(rename = "Southern Sudan")]
    SouthernSudan,
    Spain,
    #[serde(rename = "St Kitts and Nevis")]
    StKittsAndNevis,
    #[serde(rename = "St Lucia")]
    StLucia,
    Sudan,
    Suriname,
    Swaziland,
    Sweden,
    Switzerland,
    Syria,
    Tahiti,
    Tajikistan,
    Tanzania,
    Thailand,
    #[serde(rename = "The Gambia")]
    TheGambia,
    Togo,
    #[serde(rename = "Trinidad and Tobago")]
    TrinidadAndTobago,
    Tunisia,
    Turkey,
    Turkmenistan,
    UdSSR,
    Uganda,
    Ukraine,
    #[serde(rename = "United Arab Emirates")]
    UnitedArabEmirates,
    #[serde(rename = "United States")]
    UnitedStates,
    Uruguay,
    Uzbekistan,
    Venezuela,
    Vietnam,
    Wales,
    Zambia,
    Zimbabwe,
    Missing,  // Represents NULL or missing values
}

impl Country {
    pub fn from_str(s: &str) -> Self {
        match s {
            "Afghanistan" => Country::Afghanistan,
            "Albania" => Country::Albania,
            "Algeria" => Country::Algeria,
            "Andorra" => Country::Andorra,
            "Angola" => Country::Angola,
            "Antigua and Barbuda" => Country::AntiguaAndBarbuda,
            "Argentina" => Country::Argentina,
            "Armenia" => Country::Armenia,
            "Aruba" => Country::Aruba,
            "Australia" => Country::Australia,
            "Austria" => Country::Austria,
            "Azerbaijan" => Country::Azerbaijan,
            "Bahrain" => Country::Bahrain,
            "Barbados" => Country::Barbados,
            "Belarus" => Country::Belarus,
            "Belgium" => Country::Belgium,
            "Benin" => Country::Benin,
            "Bermuda" => Country::Bermuda,
            "Bolivia" => Country::Bolivia,
            "Bonaire" => Country::Bonaire,
            "Bosnia-Herzegovina" => Country::BosniaHerzegovina,
            "Brazil" => Country::Brazil,
            "Brunei Darussalam" => Country::BruneiDarussalam,
            "Bulgaria" => Country::Bulgaria,
            "Burkina Faso" => Country::BurkinaFaso,
            "Burundi" => Country::Burundi,
            "Cameroon" => Country::Cameroon,
            "Canada" => Country::Canada,
            "Cape Verde" => Country::CapeVerde,
            "Central African Republic" => Country::CentralAfricanRepublic,
            "Chad" => Country::Chad,
            "Chile" => Country::Chile,
            "China" => Country::China,
            "Chinese Taipei" => Country::Taiwan,
            "Colombia" => Country::Colombia,
            "Comoros" => Country::Comoros,
            "Congo" => Country::Congo,
            "Costa Rica" => Country::CostaRica,
            "Cote d'Ivoire" => Country::CoteDIvoire,
            "Croatia" => Country::Croatia,
            "CSSR" => Country::CSSR,
            "Cuba" => Country::Cuba,
            "Curacao" => Country::Curacao,
            "Cyprus" => Country::Cyprus,
            "Czech Republic" => Country::CzechRepublic,
            "Denmark" => Country::Denmark,
            "Djibouti" => Country::Djibouti,
            "Dominica" => Country::Dominica,
            "Dominican Republic" => Country::DominicanRepublic,
            "DR Congo" => Country::DRCongo,
            "Ecuador" => Country::Ecuador,
            "Egypt" => Country::Egypt,
            "El Salvador" => Country::ElSalvador,
            "England" => Country::England,
            "Equatorial Guinea" => Country::EquatorialGuinea,
            "Eritrea" => Country::Eritrea,
            "Estonia" => Country::Estonia,
            "Ethiopia" => Country::Ethiopia,
            "Europe" => Country::Europe,
            "Faroe Islands" => Country::FaroeIslands,
            "Finland" => Country::Finland,
            "France" => Country::France,
            "French Guiana" => Country::FrenchGuiana,
            "Gabon" => Country::Gabon,
            "Georgia" => Country::Georgia,
            "Germany" => Country::Germany,
            "Ghana" => Country::Ghana,
            "Greece" => Country::Greece,
            "Grenada" => Country::Grenada,
            "Guadeloupe" => Country::Guadeloupe,
            "Guatemala" => Country::Guatemala,
            "Guernsey" => Country::Guernsey,
            "Guinea" => Country::Guinea,
            "Guinea-Bissau" => Country::GuineaBissau,
            "Guyana" => Country::Guyana,
            "Haiti" => Country::Haiti,
            "Honduras" => Country::Honduras,
            "Hongkong" => Country::Hongkong,
            "Hungary" => Country::Hungary,
            "Iceland" => Country::Iceland,
            "India" => Country::India,
            "Indonesia" => Country::Indonesia,
            "Iran" => Country::Iran,
            "Iraq" => Country::Iraq,
            "Ireland" => Country::Ireland,
            "Isle of Man" => Country::IsleOfMan,
            "Israel" => Country::Israel,
            "Italy" => Country::Italy,
            "Jamaica" => Country::Jamaica,
            "Japan" => Country::Japan,
            "Jersey" => Country::Jersey,
            "Jordan" => Country::Jordan,
            "Jugoslawien (SFR)" => Country::JugoslawienSFR,
            "Kazakhstan" => Country::Kazakhstan,
            "Kenya" => Country::Kenya,
            "Korea, North" => Country::NorthKorea,
            "Korea, South" => Country::SouthKorea,
            "Kosovo" => Country::Kosovo,
            "Kuwait" => Country::Kuwait,
            "Kyrgyzstan" => Country::Kyrgyzstan,
            "Laos" => Country::Laos,
            "Latvia" => Country::Latvia,
            "Lebanon" => Country::Lebanon,
            "Liberia" => Country::Liberia,
            "Libya" => Country::Libya,
            "Liechtenstein" => Country::Liechtenstein,
            "Lithuania" => Country::Lithuania,
            "Luxembourg" => Country::Luxembourg,
            "Macao" => Country::Macao,
            "Madagascar" => Country::Madagascar,
            "Malawi" => Country::Malawi,
            "Malaysia" => Country::Malaysia,
            "Mali" => Country::Mali,
            "Malta" => Country::Malta,
            "Martinique" => Country::Martinique,
            "Mauritania" => Country::Mauritania,
            "Mauritius" => Country::Mauritius,
            "Mayotte" => Country::Mayotte,
            "Mexico" => Country::Mexico,
            "Moldova" => Country::Moldova,
            "Monaco" => Country::Monaco,
            "Montenegro" => Country::Montenegro,
            "Montserrat" => Country::Montserrat,
            "Morocco" => Country::Morocco,
            "Mozambique" => Country::Mozambique,
            "Netherlands" => Country::Netherlands,
            "Netherlands Antilles" => Country::NetherlandsAntilles,
            "Neukaledonien" => Country::Neukaledonien,
            "New Zealand" => Country::NewZealand,
            "Nicaragua" => Country::Nicaragua,
            "Niger" => Country::Niger,
            "Nigeria" => Country::Nigeria,
            "North Macedonia" => Country::NorthMacedonia,
            "Northern Ireland" => Country::NorthernIreland,
            "Norway" => Country::Norway,
            "Oman" => Country::Oman,
            "Pakistan" => Country::Pakistan,
            "Palestine" => Country::Palestine,
            "Panama" => Country::Panama,
            "Papua New Guinea" => Country::PapuaNewGuinea,
            "Paraguay" => Country::Paraguay,
            "Peru" => Country::Peru,
            "Philippines" => Country::Philippines,
            "Poland" => Country::Poland,
            "Portugal" => Country::Portugal,
            "Qatar" => Country::Qatar,
            "Réunion" => Country::Reunion,
            "Romania" => Country::Romania,
            "Russia" => Country::Russia,
            "Rwanda" => Country::Rwanda,
            "Saint-Martin" => Country::SaintMartin,
            "San Marino" => Country::SanMarino,
            "Sao Tome and Principe" => Country::SaoTomeAndPrincipe,
            "Saudi Arabia" => Country::SaudiArabia,
            "Scotland" => Country::Scotland,
            "Senegal" => Country::Senegal,
            "Serbia" => Country::Serbia,
            "Serbia and Montenegro" => Country::SerbiaAndMontenegro,
            "Seychelles" => Country::Seychelles,
            "Sierra Leone" => Country::SierraLeone,
            "Singapore" => Country::Singapore,
            "Sint Maarten" => Country::SintMaarten,
            "Slovakia" => Country::Slovakia,
            "Slovenia" => Country::Slovenia,
            "Somalia" => Country::Somalia,
            "South Africa" => Country::SouthAfrica,
            "Southern Sudan" => Country::SouthernSudan,
            "Spain" => Country::Spain,
            "St. Kitts & Nevis" => Country::StKittsAndNevis,
            "St. Lucia" => Country::StLucia,
            "Sudan" => Country::Sudan,
            "Suriname" => Country::Suriname,
            "Swaziland" => Country::Swaziland,
            "Sweden" => Country::Sweden,
            "Switzerland" => Country::Switzerland,
            "Syria" => Country::Syria,
            "Tahiti" => Country::Tahiti,
            "Tajikistan" => Country::Tajikistan,
            "Tanzania" => Country::Tanzania,
            "Thailand" => Country::Thailand,
            "The Gambia" => Country::TheGambia,
            "Togo" => Country::Togo,
            "Trinidad and Tobago" => Country::TrinidadAndTobago,
            "Tunisia" => Country::Tunisia,
            "Turkey" => Country::Turkey,
            "Türkiye" => Country::Turkey,
            "Turkmenistan" => Country::Turkmenistan,
            "UdSSR" => Country::UdSSR,
            "Uganda" => Country::Uganda,
            "Ukraine" => Country::Ukraine,
            "United Arab Emirates" => Country::UnitedArabEmirates,
            "United States" => Country::UnitedStates,
            "Uruguay" => Country::Uruguay,
            "Uzbekistan" => Country::Uzbekistan,
            "Venezuela" => Country::Venezuela,
            "Vietnam" => Country::Vietnam,
            "Wales" => Country::Wales,
            "Zambia" => Country::Zambia,
            "Zimbabwe" => Country::Zimbabwe,
            _ => Country::Missing,  // Default case for NULL or unrecognized values
        }
    }

    pub fn as_str(&self) -> &str {
        match self {
            Country::Afghanistan => "Afghanistan",
            Country::Albania => "Albania",
            Country::Algeria => "Algeria",
            Country::Andorra => "Andorra",
            Country::Angola => "Angola",
            Country::AntiguaAndBarbuda => "Antigua and Barbuda",
            Country::Argentina => "Argentina",
            Country::Armenia => "Armenia",
            Country::Aruba => "Aruba",
            Country::Australia => "Australia",
            Country::Austria => "Austria",
            Country::Azerbaijan => "Azerbaijan",
            Country::Bahrain => "Bahrain",
            Country::Barbados => "Barbados",
            Country::Belarus => "Belarus",
            Country::Belgium => "Belgium",
            Country::Benin => "Benin",
            Country::Bermuda => "Bermuda",
            Country::Bolivia => "Bolivia",
            Country::Bonaire => "Bonaire",
            Country::BosniaHerzegovina => "Bosnia-Herzegovina",
            Country::Brazil => "Brazil",
            Country::BruneiDarussalam => "Brunei Darussalam",
            Country::Bulgaria => "Bulgaria",
            Country::BurkinaFaso => "Burkina Faso",
            Country::Burundi => "Burundi",
            Country::Cameroon => "Cameroon",
            Country::Canada => "Canada",
            Country::CapeVerde => "Cape Verde",
            Country::CentralAfricanRepublic => "Central African Republic",
            Country::Chad => "Chad",
            Country::Chile => "Chile",
            Country::China => "China",
            Country::Taiwan => "Chinese Taipei",
            Country::Colombia => "Colombia",
            Country::Comoros => "Comoros",
            Country::Congo => "Congo",
            Country::CostaRica => "Costa Rica",
            Country::CoteDIvoire => "Cote d'Ivoire",
            Country::Croatia => "Croatia",
            Country::CSSR => "CSSR",
            Country::Cuba => "Cuba",
            Country::Curacao => "Curacao",
            Country::Cyprus => "Cyprus",
            Country::CzechRepublic => "Czech Republic",
            Country::Denmark => "Denmark",
            Country::Djibouti => "Djibouti",
            Country::Dominica => "Dominica",
            Country::DominicanRepublic => "Dominican Republic",
            Country::DRCongo => "DR Congo",
            Country::Ecuador => "Ecuador",
            Country::Egypt => "Egypt",
            Country::ElSalvador => "El Salvador",
            Country::England => "England",
            Country::EquatorialGuinea => "Equatorial Guinea",
            Country::Eritrea => "Eritrea",
            Country::Estonia => "Estonia",
            Country::Ethiopia => "Ethiopia",
            Country::Europe => "Europe",
            Country::FaroeIslands => "Faroe Islands",
            Country::Finland => "Finland",
            Country::France => "France",
            Country::FrenchGuiana => "French Guiana",
            Country::Gabon => "Gabon",
            Country::Georgia => "Georgia",
            Country::Germany => "Germany",
            Country::Ghana => "Ghana",
            Country::Greece => "Greece",
            Country::Grenada => "Grenada",
            Country::Guadeloupe => "Guadeloupe",
            Country::Guatemala => "Guatemala",
            Country::Guernsey => "Guernsey",
            Country::Guinea => "Guinea",
            Country::GuineaBissau => "Guinea-Bissau",
            Country::Guyana => "Guyana",
            Country::Haiti => "Haiti",
            Country::Honduras => "Honduras",
            Country::Hongkong => "Hongkong",
            Country::Hungary => "Hungary",
            Country::Iceland => "Iceland",
            Country::India => "India",
            Country::Indonesia => "Indonesia",
            Country::Iran => "Iran",
            Country::Iraq => "Iraq",
            Country::Ireland => "Ireland",
            Country::IsleOfMan => "Isle of Man",
            Country::Israel => "Israel",
            Country::Italy => "Italy",
            Country::Jamaica => "Jamaica",
            Country::Japan => "Japan",
            Country::Jersey => "Jersey",
            Country::Jordan => "Jordan",
            Country::JugoslawienSFR => "Jugoslawien (SFR)",
            Country::Kazakhstan => "Kazakhstan",
            Country::Kenya => "Kenya",
            Country::NorthKorea => "Korea, North",
            Country::SouthKorea => "Korea, South",
            Country::Kosovo => "Kosovo",
            Country::Kuwait => "Kuwait",
            Country::Kyrgyzstan => "Kyrgyzstan",
            Country::Laos => "Laos",
            Country::Latvia => "Latvia",
            Country::Lebanon => "Lebanon",
            Country::Liberia => "Liberia",
            Country::Libya => "Libya",
            Country::Liechtenstein => "Liechtenstein",
            Country::Lithuania => "Lithuania",
            Country::Luxembourg => "Luxembourg",
            Country::Macao => "Macao",
            Country::Madagascar => "Madagascar",
            Country::Malawi => "Malawi",
            Country::Malaysia => "Malaysia",
            Country::Mali => "Mali",
            Country::Malta => "Malta",
            Country::Martinique => "Martinique",
            Country::Mauritania => "Mauritania",
            Country::Mauritius => "Mauritius",
            Country::Mayotte => "Mayotte",
            Country::Mexico => "Mexico",
            Country::Moldova => "Moldova",
            Country::Monaco => "Monaco",
            Country::Montenegro => "Montenegro",
            Country::Montserrat => "Montserrat",
            Country::Morocco => "Morocco",
            Country::Mozambique => "Mozambique",
            Country::Netherlands => "Netherlands",
            Country::NetherlandsAntilles => "Netherlands Antilles",
            Country::Neukaledonien => "Neukaledonien",
            Country::NewZealand => "New Zealand",
            Country::Nicaragua => "Nicaragua",
            Country::Niger => "Niger",
            Country::Nigeria => "Nigeria",
            Country::NorthMacedonia => "North Macedonia",
            Country::NorthernIreland => "Northern Ireland",
            Country::Norway => "Norway",
            Country::Oman => "Oman",
            Country::Pakistan => "Pakistan",
            Country::Palestine => "Palestine",
            Country::Panama => "Panama",
            Country::PapuaNewGuinea => "Papua New Guinea",
            Country::Paraguay => "Paraguay",
            Country::Peru => "Peru",
            Country::Philippines => "Philippines",
            Country::Poland => "Poland",
            Country::Portugal => "Portugal",
            Country::Qatar => "Qatar",
            Country::Reunion => "Réunion",
            Country::Romania => "Romania",
            Country::Russia => "Russia",
            Country::Rwanda => "Rwanda",
            Country::SaintMartin => "Saint-Martin",
            Country::SanMarino => "San Marino",
            Country::SaoTomeAndPrincipe => "Sao Tome and Principe",
            Country::SaudiArabia => "Saudi Arabia",
            Country::Scotland => "Scotland",
            Country::Senegal => "Senegal",
            Country::Serbia => "Serbia",
            Country::SerbiaAndMontenegro => "Serbia and Montenegro",
            Country::Seychelles => "Seychelles",
            Country::SierraLeone => "Sierra Leone",
            Country::Singapore => "Singapore",
            Country::SintMaarten => "Sint Maarten",
            Country::Slovakia => "Slovakia",
            Country::Slovenia => "Slovenia",
            Country::Somalia => "Somalia",
            Country::SouthAfrica => "South Africa",
            Country::SouthernSudan => "Southern Sudan",
            Country::Spain => "Spain",
            Country::StKittsAndNevis => "St. Kitts & Nevis",
            Country::StLucia => "St. Lucia",
            Country::Sudan => "Sudan",
            Country::Suriname => "Suriname",
            Country::Swaziland => "Swaziland",
            Country::Sweden => "Sweden",
            Country::Switzerland => "Switzerland",
            Country::Syria => "Syria",
            Country::Tahiti => "Tahiti",
            Country::Tajikistan => "Tajikistan",
            Country::Tanzania => "Tanzania",
            Country::Thailand => "Thailand",
            Country::TheGambia => "The Gambia",
            Country::Togo => "Togo",
            Country::TrinidadAndTobago => "Trinidad and Tobago",
            Country::Tunisia => "Tunisia",
            Country::Turkey => "Turkey",
            Country::Turkmenistan => "Turkmenistan",
            Country::UdSSR => "UdSSR",
            Country::Uganda => "Uganda",
            Country::Ukraine => "Ukraine",
            Country::UnitedArabEmirates => "United Arab Emirates",
            Country::UnitedStates => "United States",
            Country::Uruguay => "Uruguay",
            Country::Uzbekistan => "Uzbekistan",
            Country::Venezuela => "Venezuela",
            Country::Vietnam => "Vietnam",
            Country::Wales => "Wales",
            Country::Zambia => "Zambia",
            Country::Zimbabwe => "Zimbabwe",
            Country::Missing => "Missing"
        }
    }

    pub fn code(&self) -> &'static str {
        match self {
            Country::Afghanistan => "af",
            Country::Albania => "al",
            Country::Algeria => "dz",
            Country::Andorra => "ad",
            Country::Angola => "ao",
            Country::AntiguaAndBarbuda => "ag",
            Country::Argentina => "ar",
            Country::Armenia => "am",
            Country::Aruba => "aw",
            Country::Australia => "au",
            Country::Austria => "at",
            Country::Azerbaijan => "az",
            Country::Bahrain => "bh",
            Country::Barbados => "bb",
            Country::Belarus => "by",
            Country::Belgium => "be",
            Country::Benin => "bj",
            Country::Bermuda => "bm",
            Country::Bolivia => "bo",
            Country::Bonaire => "bq",
            Country::BosniaHerzegovina => "ba",
            Country::Brazil => "br",
            Country::BruneiDarussalam => "bn",
            Country::Bulgaria => "bg",
            Country::BurkinaFaso => "bf",
            Country::Burundi => "bi",
            Country::Cameroon => "cm",
            Country::Canada => "ca",
            Country::CapeVerde => "cv",
            Country::CentralAfricanRepublic => "cf",
            Country::Chad => "td",
            Country::Chile => "cl",
            Country::China => "cn",
            Country::Taiwan => "tw",
            Country::Colombia => "co",
            Country::Comoros => "km",
            Country::Congo => "cg",
            Country::CostaRica => "cr",
            Country::CoteDIvoire => "ci",
            Country::Croatia => "hr",
            Country::CSSR => "cz",
            Country::Cuba => "cu",
            Country::Curacao => "cw",
            Country::Cyprus => "cy",
            Country::CzechRepublic => "cz",
            Country::Denmark => "dk",
            Country::Djibouti => "dj",
            Country::Dominica => "dm",
            Country::DominicanRepublic => "do",
            Country::DRCongo => "cd",
            Country::Ecuador => "ec",
            Country::Egypt => "eg",
            Country::ElSalvador => "sv",
            Country::England => "gb-eng",
            Country::EquatorialGuinea => "gq",
            Country::Eritrea => "er",
            Country::Estonia => "ee",
            Country::Ethiopia => "et",
            Country::Europe => "eu",
            Country::FaroeIslands => "fo",
            Country::Finland => "fi",
            Country::France => "fr",
            Country::FrenchGuiana => "gf",
            Country::Gabon => "ga",
            Country::Georgia => "ge",
            Country::Germany => "de",
            Country::Ghana => "gh",
            Country::Greece => "gr",
            Country::Grenada => "gd",
            Country::Guadeloupe => "gp",
            Country::Guatemala => "gt",
            Country::Guernsey => "gg",
            Country::Guinea => "gn",
            Country::GuineaBissau => "gw",
            Country::Guyana => "gy",
            Country::Haiti => "ht",
            Country::Honduras => "hn",
            Country::Hongkong => "hk",
            Country::Hungary => "hu",
            Country::Iceland => "is",
            Country::India => "in",
            Country::Indonesia => "id",
            Country::Iran => "ir",
            Country::Iraq => "iq",
            Country::Ireland => "ie",
            Country::IsleOfMan => "im",
            Country::Israel => "il",
            Country::Italy => "it",
            Country::Jamaica => "jm",
            Country::Japan => "jp",
            Country::Jersey => "je",
            Country::Jordan => "jo",
            Country::JugoslawienSFR => "yu",
            Country::Kazakhstan => "kz",
            Country::Kenya => "ke",
            Country::NorthKorea => "kp",
            Country::SouthKorea => "kr",
            Country::Kosovo => "xk",
            Country::Kuwait => "kw",
            Country::Kyrgyzstan => "kg",
            Country::Laos => "la",
            Country::Latvia => "lv",
            Country::Lebanon => "lb",
            Country::Liberia => "lr",
            Country::Libya => "ly",
            Country::Liechtenstein => "li",
            Country::Lithuania => "lt",
            Country::Luxembourg => "lu",
            Country::Macao => "mo",
            Country::Madagascar => "mg",
            Country::Malawi => "mw",
            Country::Malaysia => "my",
            Country::Mali => "ml",
            Country::Malta => "mt",
            Country::Martinique => "mq",
            Country::Mauritania => "mr",
            Country::Mauritius => "mu",
            Country::Mayotte => "yt",
            Country::Mexico => "mx",
            Country::Moldova => "md",
            Country::Monaco => "mc",
            Country::Montenegro => "me",
            Country::Montserrat => "ms",
            Country::Morocco => "ma",
            Country::Mozambique => "mz",
            Country::Netherlands => "nl",
            Country::NetherlandsAntilles => "an",
            Country::Neukaledonien => "nc",
            Country::NewZealand => "nz",
            Country::Nicaragua => "ni",
            Country::Niger => "ne",
            Country::Nigeria => "ng",
            Country::NorthMacedonia => "mk",
            Country::NorthernIreland => "gb",
            Country::Norway => "no",
            Country::Oman => "om",
            Country::Pakistan => "pk",
            Country::Palestine => "ps",
            Country::Panama => "pa",
            Country::PapuaNewGuinea => "pg",
            Country::Paraguay => "py",
            Country::Peru => "pe",
            Country::Philippines => "ph",
            Country::Poland => "pl",
            Country::Portugal => "pt",
            Country::Qatar => "qa",
            Country::Reunion => "re",
            Country::Romania => "ro",
            Country::Russia => "ru",
            Country::Rwanda => "rw",
            Country::SaintMartin => "mf",
            Country::SanMarino => "sm",
            Country::SaoTomeAndPrincipe => "st",
            Country::SaudiArabia => "sa",
            Country::Scotland => "gb-sct",
            Country::Senegal => "sn",
            Country::Serbia => "rs",
            Country::SerbiaAndMontenegro => "cs",
            Country::Seychelles => "sc",
            Country::SierraLeone => "sl",
            Country::Singapore => "sg",
            Country::SintMaarten => "sx",
            Country::Slovakia => "sk",
            Country::Slovenia => "si",
            Country::Somalia => "so",
            Country::SouthAfrica => "za",
            Country::SouthernSudan => "ss",
            Country::Spain => "es",
            Country::StKittsAndNevis => "kn",
            Country::StLucia => "lc",
            Country::Sudan => "sd",
            Country::Suriname => "sr",
            Country::Swaziland => "sz",
            Country::Sweden => "se",
            Country::Switzerland => "ch",
            Country::Syria => "sy",
            Country::Tahiti => "pf",
            Country::Tajikistan => "tj",
            Country::Tanzania => "tz",
            Country::Thailand => "th",
            Country::TheGambia => "gm",
            Country::Togo => "tg",
            Country::TrinidadAndTobago => "tt",
            Country::Tunisia => "tn",
            Country::Turkey => "tr",
            Country::Turkmenistan => "tm",
            Country::UdSSR => "su",
            Country::Uganda => "ug",
            Country::Ukraine => "ua",
            Country::UnitedArabEmirates => "ae",
            Country::UnitedStates => "us",
            Country::Uruguay => "uy",
            Country::Uzbekistan => "uz",
            Country::Venezuela => "ve",
            Country::Vietnam => "vn",
            Country::Wales => "gb-wls",
            Country::Zambia => "zm",
            Country::Zimbabwe => "zw",
            Country::Missing => ""
        }
    }
    pub fn from_code(code: &str) -> Country {
        match code {
            "af" => Country::Afghanistan,
            "al" => Country::Albania,
            "dz" => Country::Algeria,
            "ad" => Country::Andorra,
            "ao" => Country::Angola,
            "ag" => Country::AntiguaAndBarbuda,
            "ar" => Country::Argentina,
            "am" => Country::Armenia,
            "aw" => Country::Aruba,
            "au" => Country::Australia,
            "at" => Country::Austria,
            "az" => Country::Azerbaijan,
            "bh" => Country::Bahrain,
            "bb" => Country::Barbados,
            "by" => Country::Belarus,
            "be" => Country::Belgium,
            "bj" => Country::Benin,
            "bm" => Country::Bermuda,
            "bo" => Country::Bolivia,
            "bq" => Country::Bonaire,
            "ba" => Country::BosniaHerzegovina,
            "br" => Country::Brazil,
            "bn" => Country::BruneiDarussalam,
            "bg" => Country::Bulgaria,
            "bf" => Country::BurkinaFaso,
            "bi" => Country::Burundi,
            "cm" => Country::Cameroon,
            "ca" => Country::Canada,
            "cv" => Country::CapeVerde,
            "cf" => Country::CentralAfricanRepublic,
            "td" => Country::Chad,
            "cl" => Country::Chile,
            "cn" => Country::China,
            "tw" => Country::Taiwan,
            "co" => Country::Colombia,
            "km" => Country::Comoros,
            "cg" => Country::Congo,
            "cr" => Country::CostaRica,
            "ci" => Country::CoteDIvoire,
            "hr" => Country::Croatia,
            "cz" => Country::CzechRepublic, // Also CSSR
            "cu" => Country::Cuba,
            "cw" => Country::Curacao,
            "cy" => Country::Cyprus,
            "dk" => Country::Denmark,
            "dj" => Country::Djibouti,
            "dm" => Country::Dominica,
            "do" => Country::DominicanRepublic,
            "cd" => Country::DRCongo,
            "ec" => Country::Ecuador,
            "eg" => Country::Egypt,
            "sv" => Country::ElSalvador,
            "gb-eng" => Country::England,
            "gq" => Country::EquatorialGuinea,
            "er" => Country::Eritrea,
            "ee" => Country::Estonia,
            "et" => Country::Ethiopia,
            "eu" => Country::Europe,
            "fo" => Country::FaroeIslands,
            "fi" => Country::Finland,
            "fr" => Country::France,
            "gf" => Country::FrenchGuiana,
            "ga" => Country::Gabon,
            "ge" => Country::Georgia,
            "de" => Country::Germany,
            "gh" => Country::Ghana,
            "gr" => Country::Greece,
            "gd" => Country::Grenada,
            "gp" => Country::Guadeloupe,
            "gt" => Country::Guatemala,
            "gg" => Country::Guernsey,
            "gn" => Country::Guinea,
            "gw" => Country::GuineaBissau,
            "gy" => Country::Guyana,
            "ht" => Country::Haiti,
            "hn" => Country::Honduras,
            "hk" => Country::Hongkong,
            "hu" => Country::Hungary,
            "is" => Country::Iceland,
            "in" => Country::India,
            "id" => Country::Indonesia,
            "ir" => Country::Iran,
            "iq" => Country::Iraq,
            "ie" => Country::Ireland,
            "im" => Country::IsleOfMan,
            "il" => Country::Israel,
            "it" => Country::Italy,
            "jm" => Country::Jamaica,
            "jp" => Country::Japan,
            "je" => Country::Jersey,
            "jo" => Country::Jordan,
            "yu" => Country::JugoslawienSFR,
            "kz" => Country::Kazakhstan,
            "ke" => Country::Kenya,
            "kp" => Country::NorthKorea,
            "kr" => Country::SouthKorea,
            "xk" => Country::Kosovo,
            "kw" => Country::Kuwait,
            "kg" => Country::Kyrgyzstan,
            "la" => Country::Laos,
            "lv" => Country::Latvia,
            "lb" => Country::Lebanon,
            "lr" => Country::Liberia,
            "ly" => Country::Libya,
            "li" => Country::Liechtenstein,
            "lt" => Country::Lithuania,
            "lu" => Country::Luxembourg,
            "mo" => Country::Macao,
            "mg" => Country::Madagascar,
            "mw" => Country::Malawi,
            "my" => Country::Malaysia,
            "ml" => Country::Mali,
            "mt" => Country::Malta,
            "mq" => Country::Martinique,
            "mr" => Country::Mauritania,
            "mu" => Country::Mauritius,
            "yt" => Country::Mayotte,
            "mx" => Country::Mexico,
            "md" => Country::Moldova,
            "mc" => Country::Monaco,
            "me" => Country::Montenegro,
            "ms" => Country::Montserrat,
            "ma" => Country::Morocco,
            "mz" => Country::Mozambique,
            "nl" => Country::Netherlands,
            "an" => Country::NetherlandsAntilles,
            "nc" => Country::Neukaledonien,
            "nz" => Country::NewZealand,
            "ni" => Country::Nicaragua,
            "ne" => Country::Niger,
            "ng" => Country::Nigeria,
            "mk" => Country::NorthMacedonia,
            "gb" => Country::NorthernIreland,
            "no" => Country::Norway,
            "om" => Country::Oman,
            "pk" => Country::Pakistan,
            "ps" => Country::Palestine,
            "pa" => Country::Panama,
            "pg" => Country::PapuaNewGuinea,
            "py" => Country::Paraguay,
            "pe" => Country::Peru,
            "ph" => Country::Philippines,
            "pl" => Country::Poland,
            "pt" => Country::Portugal,
            "qa" => Country::Qatar,
            "re" => Country::Reunion,
            "ro" => Country::Romania,
            "ru" => Country::Russia,
            "rw" => Country::Rwanda,
            "mf" => Country::SaintMartin,
            "sm" => Country::SanMarino,
            "st" => Country::SaoTomeAndPrincipe,
            "sa" => Country::SaudiArabia,
            "gb-sct" => Country::Scotland,
            "sn" => Country::Senegal,
            "rs" => Country::Serbia,
            "cs" => Country::SerbiaAndMontenegro,
            "sc" => Country::Seychelles,
            "sl" => Country::SierraLeone,
            "sg" => Country::Singapore,
            "sx" => Country::SintMaarten,
            "sk" => Country::Slovakia,
            "si" => Country::Slovenia,
            "so" => Country::Somalia,
            "za" => Country::SouthAfrica,
            "ss" => Country::SouthernSudan,
            "es" => Country::Spain,
            "kn" => Country::StKittsAndNevis,
            "lc" => Country::StLucia,
            "sd" => Country::Sudan,
            "sr" => Country::Suriname,
            "sz" => Country::Swaziland,
            "se" => Country::Sweden,
            "ch" => Country::Switzerland,
            "sy" => Country::Syria,
            "pf" => Country::Tahiti,
            "tj" => Country::Tajikistan,
            "tz" => Country::Tanzania,
            "th" => Country::Thailand,
            "gm" => Country::TheGambia,
            "tg" => Country::Togo,
            "tt" => Country::TrinidadAndTobago,
            "tn" => Country::Tunisia,
            "tr" => Country::Turkey,
            "tm" => Country::Turkmenistan,
            "su" => Country::UdSSR,
            "ug" => Country::Uganda,
            "ua" => Country::Ukraine,
            "ae" => Country::UnitedArabEmirates,
            "us" => Country::UnitedStates,
            "uy" => Country::Uruguay,
            "uz" => Country::Uzbekistan,
            "ve" => Country::Venezuela,
            "vn" => Country::Vietnam,
            "gb-wls" => Country::Wales,
            "zm" => Country::Zambia,
            "zw" => Country::Zimbabwe,
            _ => Country::Missing,
        }
    }
}

