export type Country = {
    code: string;
    name: string;
};

export const countries: Country[] = [
    { code: "af", name: "Afghanistan" },
    { code: "al", name: "Albania" },
    { code: "dz", name: "Algeria" },
    { code: "ad", name: "Andorra" },
    { code: "ao", name: "Angola" },
    { code: "ag", name: "Antigua and Barbuda" },
    { code: "ar", name: "Argentina" },
    { code: "am", name: "Armenia" },
    { code: "aw", name: "Aruba" },
    { code: "au", name: "Australia" },
    { code: "at", name: "Austria" },
    { code: "az", name: "Azerbaijan" },
    { code: "bh", name: "Bahrain" },
    { code: "bb", name: "Barbados" },
    { code: "by", name: "Belarus" },
    { code: "be", name: "Belgium" },
    { code: "bj", name: "Benin" },
    { code: "bm", name: "Bermuda" },
    { code: "bo", name: "Bolivia" },
    { code: "bq", name: "Bonaire" },
    { code: "ba", name: "Bosnia and Herzegovina" },
    { code: "br", name: "Brazil" },
    { code: "bn", name: "Brunei Darussalam" },
    { code: "bg", name: "Bulgaria" },
    { code: "bf", name: "Burkina Faso" },
    { code: "bi", name: "Burundi" },
    { code: "cm", name: "Cameroon" },
    { code: "ca", name: "Canada" },
    { code: "cv", name: "Cape Verde" },
    { code: "cf", name: "Central African Republic" },
    { code: "td", name: "Chad" },
    { code: "cl", name: "Chile" },
    { code: "cn", name: "China" },
    { code: "tw", name: "Taiwan" },
    { code: "co", name: "Colombia" },
    { code: "km", name: "Comoros" },
    { code: "cg", name: "Congo" },
    { code: "cr", name: "Costa Rica" },
    { code: "ci", name: "Ivory Coast" },
    { code: "hr", name: "Croatia" },
    { code: "cz", name: "CSSR" },
    { code: "cu", name: "Cuba" },
    { code: "cw", name: "Curacao" },
    { code: "cy", name: "Cyprus" },
    { code: "cz", name: "Czech Republic" },
    { code: "dk", name: "Denmark" },
    { code: "dj", name: "Djibouti" },
    { code: "dm", name: "Dominica" },
    { code: "do", name: "Dominican Republic" },
    { code: "cd", name: "DR Congo" },
    { code: "ec", name: "Ecuador" },
    { code: "eg", name: "Egypt" },
    { code: "sv", name: "El Salvador" },
    { code: "gb-eng", name: "England" },
    { code: "gq", name: "Equatorial Guinea" },
    { code: "er", name: "Eritrea" },
    { code: "ee", name: "Estonia" },
    { code: "et", name: "Ethiopia" },
    { code: "fo", name: "Faroe Islands" },
    { code: "fi", name: "Finland" },
    { code: "fr", name: "France" },
    { code: "gf", name: "French Guiana" },
    { code: "ga", name: "Gabon" },
    { code: "ge", name: "Georgia" },
    { code: "de", name: "Germany" },
    { code: "gh", name: "Ghana" },
    { code: "gr", name: "Greece" },
    { code: "gd", name: "Grenada" },
    { code: "gp", name: "Guadeloupe" },
    { code: "gt", name: "Guatemala" },
    { code: "gg", name: "Guernsey" },
    { code: "gn", name: "Guinea" },
    { code: "gw", name: "Guinea-Bissau" },
    { code: "gy", name: "Guyana" },
    { code: "ht", name: "Haiti" },
    { code: "hn", name: "Honduras" },
    { code: "hk", name: "Hongkong" },
    { code: "hu", name: "Hungary" },
    { code: "is", name: "Iceland" },
    { code: "in", name: "India" },
    { code: "id", name: "Indonesia" },
    { code: "ir", name: "Iran" },
    { code: "iq", name: "Iraq" },
    { code: "ie", name: "Ireland" },
    { code: "im", name: "Isle of Man" },
    { code: "il", name: "Israel" },
    { code: "it", name: "Italy" },
    { code: "jm", name: "Jamaica" },
    { code: "jp", name: "Japan" },
    { code: "je", name: "Jersey" },
    { code: "jo", name: "Jordan" },
    { code: "kz", name: "Kazakhstan" },
    { code: "ke", name: "Kenya" },
    { code: "kp", name: "Korea, North" },
    { code: "kr", name: "Korea, South" },
    { code: "xk", name: "Kosovo" },
    { code: "kw", name: "Kuwait" },
    { code: "kg", name: "Kyrgyzstan" },
    { code: "la", name: "Laos" },
    { code: "lv", name: "Latvia" },
    { code: "lb", name: "Lebanon" },
    { code: "lr", name: "Liberia" },
    { code: "ly", name: "Libya" },
    { code: "li", name: "Liechtenstein" },
    { code: "lt", name: "Lithuania" },
    { code: "lu", name: "Luxembourg" },
    { code: "mo", name: "Macao" },
    { code: "mg", name: "Madagascar" },
    { code: "mw", name: "Malawi" },
    { code: "my", name: "Malaysia" },
    { code: "ml", name: "Mali" },
    { code: "mt", name: "Malta" },
    { code: "mq", name: "Martinique" },
    { code: "mr", name: "Mauritania" },
    { code: "mu", name: "Mauritius" },
    { code: "yt", name: "Mayotte" },
    { code: "mx", name: "Mexico" },
    { code: "md", name: "Moldova" },
    { code: "mc", name: "Monaco" },
    { code: "me", name: "Montenegro" },
    { code: "ms", name: "Montserrat" },
    { code: "ma", name: "Morocco" },
    { code: "mz", name: "Mozambique" },
    { code: "nl", name: "Netherlands" },
    { code: "an", name: "Netherlands Antilles" },
    { code: "nc", name: "Neukaledonien" },
    { code: "nz", name: "New Zealand" },
    { code: "ni", name: "Nicaragua" },
    { code: "ne", name: "Niger" },
    { code: "ng", name: "Nigeria" },
    { code: "mk", name: "North Macedonia" },
    { code: "gb", name: "Northern Ireland" },
    { code: "no", name: "Norway" },
    { code: "om", name: "Oman" },
    { code: "pk", name: "Pakistan" },
    { code: "ps", name: "Palestine" },
    { code: "pa", name: "Panama" },
    { code: "pg", name: "Papua New Guinea" },
    { code: "py", name: "Paraguay" },
    { code: "cg", name: "People's republic of the Congo" },
    { code: "pe", name: "Peru" },
    { code: "ph", name: "Philippines" },
    { code: "pl", name: "Poland" },
    { code: "pt", name: "Portugal" },
    { code: "qa", name: "Qatar" },
    { code: "re", name: "Réunion" },
    { code: "ro", name: "Romania" },
    { code: "ru", name: "Russia" },
    { code: "rw", name: "Rwanda" },
    { code: "mf", name: "Saint-Martin" },
    { code: "sm", name: "San Marino" },
    { code: "st", name: "Sao Tome and Principe" },
    { code: "sa", name: "Saudi Arabia" },
    { code: "gb-sct", name: "Scotland" },
    { code: "sn", name: "Senegal" },
    { code: "rs", name: "Serbia" },
    { code: "cs", name: "Serbia and Montenegro" },
    { code: "sc", name: "Seychelles" },
    { code: "sl", name: "Sierra Leone" },
    { code: "sg", name: "Singapore" },
    { code: "sx", name: "Sint Maarten" },
    { code: "sk", name: "Slovakia" },
    { code: "si", name: "Slovenia" },
    { code: "so", name: "Somalia" },
    { code: "za", name: "South Africa" },
    { code: "ss", name: "Southern Sudan" },
    { code: "es", name: "Spain" },
    { code: "kn", name: "St. Kitts & Nevis" },
    { code: "lc", name: "St. Lucia" },
    { code: "sd", name: "Sudan" },
    { code: "sr", name: "Suriname" },
    { code: "sz", name: "Swaziland" },
    { code: "se", name: "Sweden" },
    { code: "ch", name: "Switzerland" },
    { code: "sy", name: "Syria" },
    { code: "pf", name: "Tahiti" },
    { code: "tj", name: "Tajikistan" },
    { code: "tz", name: "Tanzania" },
    { code: "th", name: "Thailand" },
    { code: "gm", name: "The Gambia" },
    { code: "tg", name: "Togo" },
    { code: "tt", name: "Trinidad and Tobago" },
    { code: "tn", name: "Tunisia" },
    { code: "tr", name: "Turkey" },
    { code: "tm", name: "Turkmenistan" },
    { code: "su", name: "UdSSR" },
    { code: "ug", name: "Uganda" },
    { code: "ua", name: "Ukraine" },
    { code: "ae", name: "United Arab Emirates" },
    { code: "us", name: "United States" },
    { code: "uy", name: "Uruguay" },
    { code: "uz", name: "Uzbekistan" },
    { code: "ve", name: "Venezuela" },
    { code: "vn", name: "Vietnam" },
    { code: "gb-wls", name: "Wales" },
    { code: "zm", name: "Zambia" },
    { code: "zw", name: "Zimbabwe" }
];